### ISSUE TITLE
Support additional NCPs such as Ethernet and Wi-Fi

### ISSUE THREAD

**Issue by beriberikix** [openthread/spinel-spec#3]
It would be ideal to have future support for additional NCPs like Ethernet and WI-Fi. On the Ethernet side, [MII](https://en.wikipedia.org/wiki/Media-independent_interface) could be analgous to the Thread spec in that the definition could extend `core`. [WIZnet](http://www.shopwiznet.com/chip/internet-mcu) is a popular vendor of Ethernet controllers that could be used for prototyping, though I don't know the current status of IPv6 in their IP stack. Wi-Fi is a bit more precarious as I am not aware of standard protocols. Most vendors support AT-based commands over serial/SDIO or some proprietary (and often poorly designed) thing.

**Comment by darconeous** [comment]
Well, Ethernet and Wi-Fi are both layer-2, whereas Spinel is (currently) firmly rooted in layer-3. I'm wary of going in the direction of trying to make Spinel some sort of universal network peripheral abstraction layer.

I could see there being some sort of mesh-based firmware for an 802.11 SoC chip kinda like Thread, except using 802.11 frames instead of 802.15.4 frames. That would fit pretty well, actually.

In terms of getting buy-in at the IETF, keeping things strictly scoped to layer 3 seems like the most likely path to success (and, admittedly, the least amount of required work on my part. ;)).

**Comment by beriberikix** [comment]
Got it, makes sense to me! Thanks for the explanation :)
